spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/competitions
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    liquibase:
        drop-first: true
