spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/competitions
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    liquibase:
        drop-first: false
    jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false # disable annoying exception on Spring startup

assm:
    app:
        jwtSecret: jwtAssmSecretKey
        jwtExpiration: 86400

server:
    tomcat:
        remote-ip-header: x-forwarded-for
        protocol-header: x-forwarded-proto

